# Generated by Django 3.2.8 on 2021-11-13 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0002_topic_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic_follow',
            name='user_id',
        ),
        migrations.AddField(
            model_name='topic_follow',
            name='user_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='topic', to=settings.AUTH_USER_MODEL),
        ),
    ]
