# Generated by Django 3.1.12 on 2021-10-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
