# Generated by Django 3.1.12 on 2021-10-12 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now=True)),
                ('cmt', models.CharField(blank=True, max_length=500, null=True)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='home.post')),
                ('commentlike', models.ManyToManyField(blank=True, null=True, related_name='cmtlike', to=settings.AUTH_USER_MODEL)),
                ('userac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userac', to='home.account')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmtuid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
