# Generated by Django 3.1.12 on 2021-10-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
