# Generated by Django 3.1.12 on 2021-10-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_account_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
