# Generated by Django 3.2.8 on 2021-11-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_post_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
